In [17]:
import pandas as pd
tweets = pd.read_csv('analysed_tweets.csv',header=0, encoding="utf8")

In [18]:
tweets.head()

,id,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,593891099434983425,RT @KirkKus: Indirect cost of the UK being in ...,31150,107794703,en,804,False,False
1,593891099548094465,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
2,593891099388846080,RT @LabourEoin: The economy was growing 3 time...,7565,3006692193,en,182,False,False
3,593891100429045760,RT @GregLauder: the UKIP east lothian candidat...,2130,455154030,en,1073,False,False
4,593891100768784384,RT @thesundaypeople: UKIP's housing spokesman ...,131,187547338,en,87,False,False

In [19]:
#remove retweets by using the RT string which is present in all text field of the tweet
tweets=tweets[tweets.text.str.contains("RT")==False]

In [20]:
tweets.head()
#see below that all those retweets which appeared above are dropped.

,id,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
1,593891099548094465,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
9,593891101313896449,LOLZ to Trickle Down Wealth. It's never trickl...,2677,2471552766,en,966,False,False
10,593891101766918144,SNP leader faces audience questions http://t.c...,0,557422508,en,184,False,False
13,593891102480007169,If Miliband is refusing to do any deal with th...,492,390331913,en,174,False,False
15,593891103184551936,Cameron wins last TV contest of election campa...,4,2724103423,en,102,False,False

In [21]:
# but due to dropping those dataframe entries, disturbance in index occurred.
# so resetting the index 
tweets = tweets.reset_index(drop=True)

In [22]:
tweets.head()
# the index is back to normal

,id,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,593891099548094465,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
1,593891101313896449,LOLZ to Trickle Down Wealth. It's never trickl...,2677,2471552766,en,966,False,False
2,593891101766918144,SNP leader faces audience questions http://t.c...,0,557422508,en,184,False,False
3,593891102480007169,If Miliband is refusing to do any deal with th...,492,390331913,en,174,False,False
4,593891103184551936,Cameron wins last TV contest of election campa...,4,2724103423,en,102,False,False

In [23]:
#Now this is the dataset we need to work on as we don't have any retweets. So saving this as 'tweets_dataframe.csv'
'''Point to be noted is the generated index will also be saved if we don't mention index=False explicitly and when when we try to
print the dataframe after reading from csv file we get another column 'unamed' with the generated indexes.''' 
tweets.to_csv('tweets_dataframe.csv',index=False, sep='\t', encoding='utf-8')

In [24]:
df=pd.read_csv('tweets_dataframe.csv', sep='\t')

In [25]:
df.head()

,id,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,593891099548094465,VIDEO: Sturgeon on post-election deals http://...,0.0,557422508,en,184,False,False
1,593891101313896449,LOLZ to Trickle Down Wealth. It's never trickl...,2677.0,2471552766,en,966,False,False
2,593891101766918144,SNP leader faces audience questions http://t.c...,0.0,557422508,en,184,False,False
3,593891102480007169,If Miliband is refusing to do any deal with th...,492.0,390331913,en,174,False,False
4,593891103184551936,Cameron wins last TV contest of election campa...,4.0,2724103423,en,102,False,False